import '@/styles/globals.css';
import { TrpcProvider } from '@/app/TrpcProvider';
import { Providers } from '@/app/Theme/providers';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

// here we wrap all of our pages with TrpcProvider to enable the client to invoke RPCs

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <TrpcProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </TrpcProvider>
  );
}
